### ISSUE TITLE
Can't open sqlite3 db with uri keyword. Python 3.4 is the first version to support it

### ISSUE THREAD

**Issue by underyx** [muccg/docker-devpi#8]
```
9/14/2016 9:23:55 PMDEVPI_SERVERDIR is /data/server
9/14/2016 9:23:55 PMDEVPI_CLIENTDIR is /data/client
9/14/2016 9:23:55 PM[RUN]: Launching devpi-server
9/14/2016 9:23:56 PM2016-09-14 19:23:56,545 INFO  NOCTX Loading node info from /data/server/.nodeinfo
9/14/2016 9:23:56 PM2016-09-14 19:23:56,580 INFO  NOCTX wrote nodeinfo to: /data/server/.nodeinfo
9/14/2016 9:23:56 PM2016-09-14 19:23:56,584 WARNI NOCTX Can't open sqlite3 db with uri keyword. Python 3.4 is the first version to support it.
9/14/2016 9:23:56 PMTraceback (most recent call last):
9/14/2016 9:23:56 PM  File "/env/bin/devpi-server", line 11, in <module>
9/14/2016 9:23:56 PM    sys.exit(main())
9/14/2016 9:23:56 PM  File "/env/lib/python2.7/site-packages/devpi_server/main.py", line 56, in main
9/14/2016 9:23:56 PM    return _main(pluginmanager, argv=argv)
9/14/2016 9:23:56 PM  File "/env/lib/python2.7/site-packages/devpi_server/main.py", line 90, in _main
9/14/2016 9:23:56 PM    if not xom.is_replica() and xom.keyfs.get_current_serial() == -1:
9/14/2016 9:23:56 PM  File "/env/lib/python2.7/site-packages/devpi_common/types.py", line 39, in get
9/14/2016 9:23:56 PM    x = self._property_cache[f] = f(self)
9/14/2016 9:23:56 PM  File "/env/lib/python2.7/site-packages/devpi_server/main.py", line 249, in keyfs
9/14/2016 9:23:56 PM    cache_size=self.config.args.keyfs_cache_size)
9/14/2016 9:23:56 PM  File "/env/lib/python2.7/site-packages/devpi_server/keyfs.py", line 134, in __init__
9/14/2016 9:23:56 PM    self._storage.perform_crash_recovery()
9/14/2016 9:23:56 PM  File "/env/lib/python2.7/site-packages/devpi_server/keyfs_sqlite_fs.py", line 76, in perform_crash_recovery
9/14/2016 9:23:56 PM    if conn.last_changelog_serial == -1:
9/14/2016 9:23:56 PM  File "/env/lib/python2.7/site-packages/devpi_common/types.py", line 39, in get
9/14/2016 9:23:56 PM    x = self._property_cache[f] = f(self)
9/14/2016 9:23:56 PM  File "/env/lib/python2.7/site-packages/devpi_server/keyfs_sqlite.py", line 33, in last_changelog_serial
9/14/2016 9:23:56 PM    return self.db_read_last_changelog_serial()
9/14/2016 9:23:56 PM  File "/env/lib/python2.7/site-packages/devpi_server/keyfs_sqlite.py", line 37, in db_read_last_changelog_serial
9/14/2016 9:23:56 PM    res = self._sqlconn.execute(q).fetchone()[0]
9/14/2016 9:23:56 PMsqlite3.OperationalError: no such table: changelog
```

**Comment by aahunter** [comment]
Is this an upgrade issue? Does this ticket help:

https://bitbucket.org/hpk42/devpi/issues/365/devpi-server-410-internal-server-error

**Comment by underyx** [comment]
Actually, looks like the issue might have been caused by the volume being
broken. Please close the issue if you cannot reproduce.

**Comment by aahunter** [comment]
Closing as we don't see this issue.
